#define KB (1024)
#define MB (1024 * KB)
#define GB (1024 * MB)

#define PART_PRELOADER "PRELOADER" 
#define PART_MBR "MBR" 
#define PART_EBR1 "EBR1" 
#define PART_PMT "PMT" 
#define PART_PRO_INFO "PRO_INFO" 
#define PART_NVRAM "NVRAM" 
#define PART_PROTECT_F "PROTECT_F" 
#define PART_PROTECT_S "PROTECT_S" 
#define PART_SECCFG "SECCFG" 
#define PART_UBOOT "UBOOT" 
#define PART_BOOTIMG "BOOTIMG" 
#define PART_RECOVERY "RECOVERY" 
#define PART_SEC_RO "SEC_RO" 
#define PART_MISC "MISC" 
#define PART_LOGO "LOGO" 
#define PART_EBR2 "EBR2" 
#define PART_EXPDB "EXPDB" 
#define PART_ANDROID "ANDROID" 
#define PART_CACHE "CACHE" 
#define PART_USRDATA "USRDATA" 
#define PART_FAT "FAT" 
#define PART_BMTPOOL "BMTPOOL" 
/*preloader re-name*/
#define PART_SECURE "SECURE" 
#define PART_SECSTATIC "SECSTATIC" 
#define PART_ANDSYSIMG "ANDSYSIMG" 
#define PART_USER "USER" 
/*Uboot re-name*/
#define PART_APANIC "APANIC" 

#define PART_FLAG_NONE 0 
#define PART_FLAG_LEFT 0x1 
#define PART_FLAG_END 0x2 
#define PART_MAGIC 0x58881688 

#define PART_SIZE_PRELOADER (6144*KB)
#define PART_SIZE_MBR (512*KB)
#define PART_SIZE_EBR1 (512*KB)
#define PART_SIZE_PMT (4096*KB)
#define PART_SIZE_PRO_INFO (3072*KB)
#define PART_SIZE_NVRAM (5120*KB)
#define PART_SIZE_PROTECT_F (10240*KB)
#define PART_SIZE_PROTECT_S (10240*KB)
#define PART_SIZE_SECCFG (128*KB)
#define PART_OFFSET_SECCFG (0x2700000)
#define PART_SIZE_UBOOT (384*KB)
#define PART_SIZE_BOOTIMG (6144*KB)
#define PART_SIZE_RECOVERY (6144*KB)
#define PART_SIZE_SEC_RO (6144*KB)
#define PART_OFFSET_SEC_RO (0x3380000)
#define PART_SIZE_MISC (512*KB)
#define PART_SIZE_LOGO (3072*KB)
#define PART_SIZE_EBR2 (512*KB)
#define PART_SIZE_EXPDB (10240*KB)
#define PART_SIZE_ANDROID (665600*KB)
#define PART_SIZE_CACHE (129024*KB)
#define PART_SIZE_USRDATA (1048576*KB)
#define PART_SIZE_FAT (0*KB)
#define PART_SIZE_BMTPOOL (0xa8)


#define PART_NUM 22